services:
  web:
    build: ./web-flask
    ports:
      - "8000:5000"
    depends_on:
      - api
      - init
  api:
    build: ./api-flask
    ports:
      - "5001:5001"
    depends_on:
      - init
      - kafka
  match-updater:
    build: ./match-updater-py
    depends_on:
      - api
      - kafka
  simple-average:
    build: ./simple-average-py
    depends_on:
      - api
      - kafka
      - init
  kafka:
    image: 'bitnami/kafka:latest'
    ports: 
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  init:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic match-results --replication-factor 1 --partitions 1
 
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
